### ISSUE TITLE
jdk9 support change

### ISSUE THREAD

**Issue by scottmarlow** [jboss/jboss-jstl-api_spec#15]
changing jboss-parent to be 21, avoids "[WARNING] Error injecting: org.codehaus.plexus.archiver.jar.JarArchiver":

> java.lang.ArrayIndexOutOfBoundsException: 1
> 	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.<clinit>(AbstractZipArchiver.java:116)
>

**Comment by ctomc** [comment]
fixed
